# Generated by Django 5.1.1 on 2024-10-18 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reviewsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='reviewsystem.organization'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'organization')},
        ),
        migrations.CreateModel(
            name='UserOrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewsystem.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewsystem.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewsystem.user')),
            ],
            options={
                'unique_together': {('user', 'organization', 'role')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='assignmentrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignmentrole',
            name='user_organization_role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviewsystem.userorganizationrole'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentrole',
            unique_together={('assignment', 'user_organization_role')},
        ),
        migrations.DeleteModel(
            name='OrganizationRole',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.RemoveField(
            model_name='assignmentrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='assignmentrole',
            name='user',
        ),
    ]
