# Generated by Django 5.1.1 on 2024-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsystem', '0003_user_date_of_joining_user_enrollment_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrollment_no',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
